from enum import Enum
from typing import Dict, List, Optional
from pydantic import BaseModel, Field


class InjectionVector(str, Enum):
    """The 5 attack injection vectors supported by PHANTOM."""
    DIRECT_PROMPT = "direct_prompt"
    TOOL_OUTPUT_SPOOFING = "tool_output_spoofing"
    RAG_POISONING = "rag_poisoning"
    SYSTEM_PROMPT_INJECTION = "system_prompt_injection"
    MEMORY_BACKDOOR = "memory_backdoor"


class AdversarialPayload(BaseModel):
    """Synthesized adversarial payload crafted by PHANTOM."""
    payload_id: str
    vector: InjectionVector
    target_belief: str = Field(..., description="Target false premise to inject into agent world model")
    payload_text: str = Field(..., description="Constrained decoded natural language payload")
    injection_step: int = Field(..., description="Turn index at which injection occurs")
    metadata: Dict[str, str] = Field(default_factory=dict)


class AttackTrajectory(BaseModel):
    """Execution trace of an attack rollout generated by ARCHITECT / PHANTOM."""
    attack_id: str
    target_pipeline: str
    payloads: List[AdversarialPayload] = Field(default_factory=list)
    cascade_depth: int = Field(default=0, description="Downstream agent steps corrupted")
    is_detected: bool = Field(default=False, description="Flagged by AEGIS detection middleware")
    score: float = Field(default=0.0, description="NEMESIS RL reward score")
